fos_elastica:
    clients:
        default:
            url: 'http://elasticsearch:9200'
    indexes:
      publications:
          persistence:
              driver: orm
              model: App\Entity\Publication
              provider: 
                query_builder_method: createIsNotSoldQueryBuilder
              finder: ~
              elastica_to_model_transformer:
                hydrate: true
          properties:
              id: ~
              description:
                  type: text
              price:
                  type: float
              year:
                  type: integer
              brand:
                  type: nested
                  properties:
                      id: ~
                      name: { type: keyword }
              model:
                  type: nested
                  properties:
                      id: ~
                      name: { type: keyword }
              motorizationType:
                  type: nested
                  properties:
                      id: ~
                      name: { type: keyword }
              country:
                  type: nested
                  properties:
                      id: ~
                      name: { type: keyword }
              sellerLocation:
                  type: nested
                  properties:
                      id: ~
                      name: { type: keyword }                      
              user:
                  type: nested
                  properties:
                      id: ~
                      email: { type: keyword }
              mileage:
                  type: integer
              fuelType:
                  type: keyword
              gearbox:
                  type: keyword
              condition:
                  type: keyword
              hasWarranty:
                  type: boolean
              isImport:
                  type: boolean
              saleStatus:
                  type: nested
                  properties:
                      id: ~
                      sold: { type: boolean }
                      saleDate: { type: date }