framework:
    messenger:
        # Enable the failure transport
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: chat
            # Add the failed transport configuration
            failed:
                dsn: 'doctrine://default?queue_name=failed'

        routing:
            'App\Message\Chat\SendChatMessage': async

        # Add serializer configuration
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
