FROM nginx:stable-alpine

# Create directories with correct paths
RUN mkdir -p /var/www/html/public/build \
    /var/cache/nginx \
    /var/run/nginx \
    && chown -R nginx:nginx /var/cache/nginx \
    && chown -R nginx:nginx /var/run/nginx

# Copy configs only
COPY docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY docker/nginx/default_prod.conf /etc/nginx/conf.d/default.conf

# Set permissions
RUN chown -R nginx:nginx /var/www/html/public && \
    chmod -R 755 /var/www/html/public

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]