FROM nginx:latest

# Copy custom Nginx configuration file
COPY docker/nginx/default_prod.conf /etc/nginx/conf.d/default.conf

# Set working directory
WORKDIR /var/www/html

# Copy the application files
COPY src /var/www/html/src

# Ensure the permissions are correct for all files including build directory
RUN chown -R www-data:www-data /var/www/html/src && \
    chmod -R 755 /var/www/html/src && \
    chmod -R 775 /var/www/html/src/public/build

# Create necessary directories if they don't exist
RUN mkdir -p /var/www/html/src/public/build && \
    mkdir -p /var/www/html/src/public/tarteaucitron && \
    chown -R www-data:www-data /var/www/html/src/public

EXPOSE 80