root_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /en
        permanent: true

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: '/{_locale}'
    requirements:
        _locale: 'en|sq'
    defaults:
        _locale: 'en'